### ISSUE TITLE
Add 2015 OS forward dated ward polygons

### ISSUE THREAD

**Issue by dracos** [mysociety/mapit#152]
OS have published some ward changes for next May's election in advance, which is nice:
http://www.ordnancesurvey.co.uk/business-and-government/help-and-support/products/boundary-line.html
http://www.ordnancesurvey.co.uk/docs/support/forward-dated-ward-polygon-boundaries.pdf

Possibilities:
* Add to mapit.mysociety.org directly now in a future generation – would probably be more work when Boundary-Line comes out to then match up as these shapes are not in the same format/metadata;
* Add to a new separate mapit installation (along with non-changing council wards I assume) and advertise that for 2015 local election "finding out what ward you're in";
* Add to a new separate mapit installation, update mapit.mysociety.org so that it queries that installation on lookup with a future generation and includes the results in a separate key or with special IDs or similar.

**Comment by BenJam** [comment]
would option 1 and 3 mean that users of the API would have to make a call to find out the latest generation, would this make using the API more difficult as a developer? If so I'd vote for option 2, otherwise option 3 seems like a nice balance.

**Comment by dracos** [comment]
I think finding the generation ID is no harder than finding the URL of a totally separate MapIt :-) You wouldn't have to make a call each time, no, if you were doing something with these boundaries you'd just hard-code it once. Either way, you'd have to look at wherever this was documented. My personal preference is 2 or 3, due to the updating issues with 1.

**Comment by stevenday** [comment]
An update on where I'm at with this. 

I've gone with importing the shapefiles into a new mapit as @dracos preferred, since the new data doesn't contain any kind of identifiers other than ward names, so I agree that trying to update it later would be a pain. 

I've tried getting the import script to update existing areas based on matching the names, but realised that this won't work because: A) the files are various different types of area as far as mapit is concerned (DIW, UTW, etc), and B) the names OS has given them in the new files don't always match existing areas. So, to make it absolutely clear, I'll import them under a new `area_type` code like `15W` so that the new ones are totally obvious. As a bonus, this'll mean you can compare old/new wards for a postcode in one api request. 

For now I've done this on top of an untouched copy of the current live DB, so that you can continue see parent areas and so on, but I could remove them if we want to make this just about wards?

There have been a few issues with the data:
- Some of the data files have shapes with NULL names in (I've amended the import command to skip those as a workaround)
- The files contain LINESTRING and MULTILINESTRING features, not polygons (I've amended the import command to convert them to Polygons using their `convex_hull` method as a workaround. I'm aware that this can alter the output though)
- The files are marked as being UTF-8 encoded, but contain Windows encoded apostrophe's which Django chokes on. (I've opened and re-saved the files in QGIS to fix this, although it has found a small bug in the `mapit_import command, so thanks OS!)

The big one here is having to create Polygons from the LineStrings. @dracos: is there a better way to do that than `convex_hull`?

**Comment by dracos** [comment]
For a line string, something like this should work (I assume they should all actually be linear rings!):
```
>>> l = LineString((0,0), (1,0), (0,1), (0,0))
>>> r = LinearRing(*l)
>>> p = Polygon(r)
```

For the multi line strings, I'm not sure if you can work out if they're holes or separate shapes… Are there many of these? Probably easiest just to loop through them and turn each one into a polygon as above, and see if that makes anything horribly wrong anywhere.

**Comment by stevenday** [comment]
@dracos: thanks for that - there are 5 boundaries which are MultiLineStrings, and each of them is (I think) an error on the behalf of OS (They're all formed of tiny holes at the edges with one or two points in them). I've tried to fix these manually in QGIS, but because of the way features are defined in the files, everything starts to unravel :( 

I think fix_invalid_polygons would be able to sort these out, but because I can't get them into a Polygon in the first place, I'm not sure how to run it against them.

For now, I've ignored them. For reference, they are:
- Priorslee
- Newport South and East
- Nacton and Purdis Farm
 - Wellesbourne East
- The Ampneys and Hampton

That seems to have been the last of the issues, so now that I've actually managed to get everything into the database, I'll move my db up onto a staging site for a review.

**Comment by dracos** [comment]
I would just check the length and ignore the second part if too small. 100m would do it (25m ignoring Ampneys), and then just treat as a LineString.

**Comment by dracos** [comment]
Done in 2015wards repo.

**Comment by ohdannyboy1664** [comment]
Stunning! Thank you :-)

**Comment by ohdannyboy1664** [comment]
Thanks very much for doing this. 

Is there any way of displaying just the new ward area? I'm not a coder, more of a poker, so I'm looking for a URL/KML to display the (just) new ward map.

For example taking the new Ashdon ward in Essex. Putting in a postcode into the lookup box returns this page: http://2015wards.mysociety.org/postcode/CB101XA, but I am trying to display just the new ward map. For the old one it would be http://mapit.mysociety.org/area/135051.html with the (ward) area ID "135051" inserted in the URL string.

Looking through the source code for http://2015wards.mysociety.org/postcode/CB101XA I'm struggling to find the area IDs. The code only seems to have 2 areas 1123 and 10022. Neither of which work/are correct in the string http://mapit.mysociety.org/area/xxxx.html or a string http://2015wards.mysociety.org/area/1123.html , or even http://mapit.mysociety.org/2015wards/1123.html. 

Any guidance on how to achieve this?

Thx in advance.

**Comment by dracos** [comment]
The second ID in the source (10022 in your example) is the area ID of the new ward on this site (the IDs are independent of the main MapIt); you can get a KML of it at http://2015wards.mysociety.org/area/10022.kml (with optionally the simplify_tolerance parameter as in the source), and I've added an HTML view now at http://2015wards.mysociety.org/area/10022.html

**Comment by ohdannyboy1664** [comment]
Great thanks! And for the quick response.
