### ISSUE TITLE
Northern Ireland Eurpoean Region

### ISSUE THREAD

**Issue by garrilla** [mysociety/mapit#166]
It displays an small area, presumably a ward or parish...

http://mapit.mysociety.org/area/16869.html

**Comment by davewhiteland** [comment]
Fwiw that's http://en.wikipedia.org/wiki/Rathlin_Island

**Comment by garrilla** [comment]
@davewhiteland thanks for the info, but it is supposed to be NI European Region.

**Comment by davewhiteland** [comment]
@garrilla yes indeed -- sorry, my comment wasn't intended as a remedy, just as a point of information, as I didn't even know what that area was when I saw the map.

**Comment by dracos** [comment]
The HTML pages display a slightly simplified version of the boundaries for performance reasons, using the `simplify_tolerance` parameter. However, due to the way this particular boundary was constructed from other boundaries, when it is slightly simplified the main boundary (of the whole mainland) disappears in the simplification, and you're left with Rathlin Island, the other boundary within the geometry. The full GeoJSON of the boundary is fine, however.

**Comment by dracos** [comment]
I have cleaned the shape and the page displays okay now, thanks.

**Comment by garrilla** [comment]
Thanks.

**Comment by dracos** [comment]
Can I ask about your interest in this boundary in particular, or were you just browsing? In general, it's better to use/rely on smaller boundaries due to the performance issues with large boundaries.

**Comment by garrilla** [comment]
Hi,

I was looking for a UK regions for a mapping app - I could find GB regions but not a NI region.

I haven't checked your licence yet, but if I'm able to use it I'm likely to simplify it with topoJSON.
