### ISSUE TITLE
Allow users to register for accounts on MapitGB

### ISSUE THREAD

**Issue by stevenday** [mysociety/mapit#173]

**Comment by stevenday** [comment]
I'm thinking of using https://github.com/macropin/django-registration to do this (the Django 1.7 compatible django-registration app). It should cover all of our needs as far as user registration and login/logout/password reset etc. 

However, this will require adding additional dependencies to the mapit project and I'm not sure what the best of doing that is. @dracos @mhl do you have any thoughts? 

My main worry is that while we want user registration (and future api key management functionality) on MapitGB, we don't want to force everyone else who re-uses the apps/project to install it, nor complicate the install process by needing to add other stuff to `settings.py`. 

Should I just add the `django-registration` app to `INSTALLED_APPS` inside an appropriate conditional [like we do already for country-specific apps](https://github.com/mysociety/mapit/blob/master/project/settings.py#L238-L243), or should I build in an extra layer where country apps can specify other apps they need?

In either case, I'll also need to add django-registration (and any future api management app) to the package requirements. Should I just bung them into `install_requires` in setup.py, or do something cleverer with [extras_require](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) so that they're optional? (I think I'd need to add a different `post_deploy_actions.bash` to install mapit with the optional extras in that case, but this is all getting a bit out of my comfort zone).

**Comment by dracos** [comment]
Perhaps this is a case for mapitGB being a separate repository, including mapit in its requirements like any other package, rather than sticking to the built-in example project?

If not, you could do as you say with conditional adding of apps; on the last point, no, it shouldn't be in setup.py, if it's just specific to your installation, then I think it should be installed separately outside the installation of mapit. Which points to it being a separate project repo really.

**Comment by dracos** [comment]
Being dealt with in separate repo.
