### ISSUE TITLE
MapIt (Global) promotional site looks dated

### ISSUE THREAD

**Issue by zarino** [mysociety/mapit#220]
This was brought up at our 2015 annual retreat.

Some people feel the site looks very dated, especially when compared to similar sites like EveryPolitician.

Looks aside, it does a good job of documenting the API. But, if we want to encourage commercial reuses of MapIt, the site could do a better job of promoting the service, suggesting ways it can be used, or showing examples of MapIt in use elsewhere on the web.

![screen shot 2015-12-14 at 13 55 50](https://cloud.githubusercontent.com/assets/739624/11782691/66412210-a26a-11e5-9083-56470634080c.png)

**Comment by zarino** [comment]
Thoughts:

* Why are there two separate sites for UK vs Global?
* We'll need new text – general text for describing the service, and specific sales text about how it can be used. /cc @MyfanwyNixon

**Comment by davewhiteland** [comment]
This isn't a defence of having multiple sites, but perhaps it's an explanation. The short answer is: because it's simpler to run two sites -- they're behaving differently enough for it to be more work than it's worth to combine them.

The difference between the sites is a functional one: the `UK` and `global` sites serve different data because it comes from different sources (you can see one consequence of this by comparing the data licenses at the footer of http://global.mapit.mysociety.org/ and http://mapit.mysociety.org/). After all, people can (and do!) take a MapIt and load it with any data, and indeed we have done just this with the "third" mySociety general MapIt. We run that third installation (called `international`) so we can load it with custom as-needed shapes we've drawn ourselves for specific FMS installations in places that OpenStreetMap hasn't got covered (yet). (Incidentally, that's why that one isn't advertised because it's unlikely to be useful beyond our own needs. Also, we encourage anyone who needs (or has) good boundary data to add it to OSM (and thence it will appear in global MapIt, of course)). 

Consequently, even if you just ask for areas, you get different results from the different services:

* http://mapit.mysociety.org/point/4326/-0.1275,51.507222.html
* http://global.mapit.mysociety.org/point/4326/-0.1275,51.507222.html

One clear difference that results from this is that UK MapIt has postcode data in it, so it offers a postcode API call which global MapIt does not.
 
I'm not sure but I suspect we're running separate rate-limiting on those servers two. All these *could* be rolled into one single service, but I'm not convinced of who's benefiting from making the entry point simpler in return for more complexity in understanding the mix of data the caller sometimes be getting back, and the potential overhead we'd need to add to allow requests to choose which data sets they wanted included in the response.

**Comment by davewhiteland** [comment]
Note I think this is related to https://github.com/mysociety/mapit/issues/75 -- currently those other MapIts, installed in diverse countries around the world such as our Sinar friends' MapIt at http://mapit.sinarproject.org/ , all look a lot like global and/or uk MapIt, and would benefit from much the same kind of thought process that's being applied to those two. Design team might already be aware of that but I'm flagging it here anyway to be sure: basically the information/message being conveyed stands to benefit all MapIts, but should also allow customisation (we have three special cases, two of which we're keep to promote, ourselves).

**Comment by BenJam** [comment]
One might suggest that http://mapit.poplus.org/ is actually the closest thing we have to a sales-based site for mapit and that folding content from one into the other would be a quick fire solution.

**Comment by abimysoc** [comment]
https://github.com/mysociety/mapit/pull/280 has made the cosmetic improvements.
