### ISSUE TITLE
Pip install mapit, data directory for mapit_gb/data only contains 1 file

### ISSUE THREAD

**Issue by bee-keeper** [mysociety/mapit#282]
Hi,

Maybe I'm missing something here.  If I git clone the repo I see the data directory for `mapit_gb/data` has all the expected data files.  However, if I pip install the app, my `.venv/lib/python3.5/site-packages/mapit_gb/data` directory contains only `initial-fix-ups.sql`

Obviously I can copy the files in there, just wondering why this is the case though?

Thanks

**Comment by dracos** [comment]
It looks like the manifest might be out-of-date (it lists `data` rather than `mapit_gb/data`); however, pip installing is generally for people embedding the software within something else, who probably don't need the specific data in this directory. I guess `gss-to-local-authority-eng.tsv` should be included given a new management script refers to it, but we should really factor out the UK-specific data/scripts/etc to a separate repository. Most of it is now very out of date anyway (e.g. as we now have NI boundaries, there's no need for all the special NI handling).

**Comment by bee-keeper** [comment]
Ok thanks for the reply.  Sounds like fixing this is part of a larger refactor so I'll close.
