### ISSUE TITLE
Importing new boundary lines data failing

### ISSUE THREAD

**Issue by MuriloDalRi** [mysociety/mapit#360]
I'm trying to import the new boundary lines data but it seems like it is in a single `.gpkg` file and the `mapit_UK_import_boundary_line` script expects a different format (`.shp`).

Does the script need to be updated?

Thank you

**Comment by dracos** [comment]
Hi, a number of issues fall out of your simple question, I'm afraid.

Firstly, ignoring your question, the important point is - do you want to import the new Boundary-Line data? Ordnance Survey appear to have included the changes to boundaries that would have been made due to the 2020 elections, but the 2020 elections were postponed to 2021 by section 60 of the Coronavirus Act 2020. Therefore the current Boundary-Line product, as I understand it, is for all intents and purposes incorrect and corrupt (given it mixes current, new, and pending data). Importing the new boundaries when they are not in force, depending on your application, may cause confusion.

Now to answer your actual question - it would be good if the script could support Geopackage, but yes, I imagine the script would need updating to support it. Ordnance Survey still supply the data also as Shapefiles, so there shouldn't be an issue - https://www.ordnancesurvey.co.uk/opendatadownload/products.html lets you ask for whatever type of data you want.

If you're talking about the cache mySociety has of some Ordnance Survey products, I've now uploaded the Shapefile version of the data there now too, but I don't really want to hold multiple copies of the same data simply in different formats, we don't have infinite disc space. Hopefully we can get the script to work with Geopackages and then never look at Shapefiles again.

**Comment by dracos** [comment]
I emailed OS the same day I wrote the above reply. I have heard back from OS today:

> Please accept my apologies for the delay in getting back to you regarding this enquiry.
> We are now fixing the boundaries that didn’t become operative in May 2020 due to there being no elections.  We are planning for these amended boundaries to go out in the October 2020 Boundary Line release.
> Again, I am sorry for the delay and thank you for your patience.

So IMO the May 2020 Boundary-Line, as I mention above, should be considered a corrupt data source and ignored.
