### ISSUE TITLE
Running `mapit_UK_add_2020_structural_changes` using May 2019 Boundary Line data

### ISSUE THREAD

**Issue by deborahchua** [mysociety/mapit#364]
Hi,

Due to this issue https://github.com/mysociety/mapit/issues/356 being raised for 2020 boundary line data and as we are still on `V1` of Django, I'm importing the May (August update) 2019 data, and trying to apply possible 2020 updates on top of this.

After importing the May 2019 boundary line data I applied the script [mapit_UK_add_2020_structural_changes](https://github.com/mysociety/mapit/commit/184473f1e188f9ab0019e7ca0a419d19b3a5d431), however there now seems to be some missing areas for many of the postcodes I tried.

I was wondering if there's a step I missed, or whether it just simply not possible using this script on older BL data?

**Comment by dracos** [comment]
#356 is not an issue with 2020 Boundary-Line. It is an issue with the 2015 NI data when imported on a system using GDAL3. As per my comment at the end of #356, Django 1.11 officially supports GDAL 1.9-2.1. Importing the May 2020 Boundary-Line should be fine, whatever versions, I would hope.

You need to run the script with a new inactive generation existing; I'm not sure what would happen if it didn't have one (I'd hope it would error, but perhaps it would not and cause the issue you describe). So that's my guess as to what happened, if you have some areas now lacking generation IDs you could reset them back to your current generation, create a new generation and then run the script again.

**Comment by dracos** [comment]
Actually I see the October 2020 Boundary-Line is now out, so that should be the latest data. OS haven't put up a release note for it, though, sigh.

**Comment by dracos** [comment]
Oh except I forgot they had messed up everything hadn't they: https://github.com/mysociety/mapit/issues/360#issuecomment-651728407

**Comment by dracos** [comment]
I'll look at scheduling in looking at the October 2020 BL this week to see if it's okay and whether it has any issues, which would probably then help you with your import if you can then just import the October 2020 edition without problem.

**Comment by dracos** [comment]
(https://github.com/mysociety/mapit/issues/365 has notes on October 2020 BL.)

**Comment by deborahchua** [comment]
Hi @dracos , thanks for looking into this. Sorry I forgot to mention, I did try the October 2020 Boundary-Line data, but was getting similar output to https://github.com/mysociety/mapit/issues/356#issue-618217543, so following the discussion on there, we decided to try and use May 2019 data instead(!)

I saw you've opened https://github.com/mysociety/mapit/issues/365 so I will follow the updates on there.

Many thanks again!

**Comment by dracos** [comment]
So, if you are inputting this data into a new empty database, and you do not care about wards/constituencies/other things with a parent relationship (so no need to run `find_parents`), I think you should be able to import the October 2020 Boundary-Line directly from scratch. When you say "similar output" to 356, my guess is that because October 2020 Boundary-Line has CEDs and DIWs for Buckinghamshire but has removed the relevant CTY/DIS (as they no longer exist), find_parents would die because it cannot find the parent it is looking for for those CEDs and DIWs. If that makes sense, do ask if you'd like me to expand further.

If you do need to run `find_parents` for your use case, then we're going to have to think how to have this work; probably we're going to have to hard code some exception here so it can map those CEDs and DIWs to the Buckinghamshire Council UTA.

**Comment by deborahchua** [comment]
Unfortunately we do need the parent data 😔 Our GOV.UK services (such as the [Covid postcode checker](https://www.gov.uk/find-coronavirus-local-restrictions)) are reliant on having the most up to date postcodes and boundaries for our users.

It would be hugely appreciated if you could prioritise a fix for this!

**Comment by dracos** [comment]
find_parents will now let UTA be a parent to a CED or a DIW (which has not happened before, as explained), so should run okay on a empty database import of the October 2020 Boundary-Line. I think that's how you normally use it, as I understand it.

If you need to import the new data into an existing database (as we do on mapit.mysociety.org), there is also now a 2020-10 control file that should work for this situation, though this has only been tested on our own database.

**Comment by deborahchua** [comment]
Hi @dracos , many thanks for looking into this and setting up https://github.com/mysociety/mapit/pull/367 

I've been importing the data into a new empty database and it hasn't had any issues using your code updates.

After activating the generation, we [run this script](https://github.com/alphagov/mapit/blob/master/mapit_gb/management/commands/mapit_UK_show_missing_codes.py)
 which returns as part of the output:

```
  1 UTA areas have no ons code:
    Buckinghamshire Council 1767 (gen 1-1) England
```

I was wondering if you have any suggestions on where I could manually assign the ONS code to Buckinghamshire in the code? 
I've also tried adding it to [this custom script we have ](https://github.com/alphagov/mapit/blob/master/mapit_gb/management/commands/mapit_UK_add_missing_codes.py), adding it to the [missing_codes list](https://github.com/alphagov/mapit/blob/master/mapit_gb/management/commands/mapit_UK_add_missing_codes.py#L22) 
but it returns `mapit.models.DoesNotExist: Area matching query does not exist.`, so I'm thinking I have set this at an earlier point 🤔

**Comment by dracos** [comment]
As a quick reply - Buckinghamshire Council has ONS code E06000060 in the October 2020 Boundary-Line data, so I'm not sure how you have imported this into an empty database and ended up with an area without a code. (And not relevant, but my old `mapit_UK_add_2020_structural_changes` script would also create an area with code E06000060.)
Is there any way you can investigate how that has happened? Because at first glance I can't see how you can end up in that situation, given what you have said.

**Comment by dracos** [comment]
It looks like your missing_codes entry doesn't work because the council name at https://github.com/alphagov/mapit/blob/9d624536dcf572ac947e00f69c535cfbbf50f355/mapit_gb/management/commands/mapit_UK_add_missing_codes.py#L72 is not the full name, so it did not match. But I don't think you should need to be using that route, for what it's worth, as far as I can see, unless I've missed something (always possible!).

**Comment by deborahchua** [comment]
Ah thanks for spotting that! I've been looking at this for too long 😅  I've just run it again with the full name `Buckinghamshire Council` but it still returns the same error.

Hmm, originally I ran the import without manually adding anything for Buckinghamshire Council and I still had the same output  which led me down this path. 

I'll have a think about this over lunch and see what else I can try.

**Comment by dracos** [comment]
If you run import_boundary_line, even without commit, it should print all the new areas it's adding, so you should be able to look at that and see what the output is for any Buckinghamshire line.

**Comment by dracos** [comment]
"I've just run it again with the full name Buckinghamshire Council but it still returns the same error." - that does imply something weird going on then, if you can't even find the row.

**Comment by deborahchua** [comment]
I've just had a look through the output and I can see it's got `New area: UTA E06000060 176443 Buckinghamshire`, so you're right, I shouldn't have to add it manually. At least I can rule that out now!
