### ISSUE TITLE
Wrong area-type CED for Buckinghamshire Council wards?

### ISSUE THREAD

**Issue by torotil** [mysociety/mapit#370]
On my fresh import and also on the current mysociety site I think the new Buckinghamshire Council Wards have got the wrong area type. They are still listed as CED instead of UTW which I would expect. This also creates the unusual situation that a CED area has a UTA area as parent.

I have grepped through the code to find any related scripts that would fix that but I couldn’t find them.

Here is an example of such a ward: https://mapit.mysociety.org/area/164030.html

Do we expect this wards to have the CED area type or is there something wrong with the import?

**Comment by dracos** [comment]
This data is correct, and is due to the unique situation caused by the coronavirus and the cancellation of the 2020 elections. You can see the history in the comments on https://github.com/mysociety/mapit/issues/365 - specifically https://github.com/mysociety/mapit/issues/365#issuecomment-721020188 : "OS have confirmed this is deliberate because of the Situation they are considering the old wards/EDs to still exist (as elections have not yet taken place for Buckinghamshire to use its new wards), although the district councils have gone and the new unitary council does exist." So the Buckinghamshire UTA does now have CPC, CED, and DIW children, because the UTW wards you refer to are not yet in force.

**Comment by torotil** [comment]
Thanks! Sorry for not finding the #365 on my own.
